### ISSUE TITLE
escaping in inner modes

### ISSUE THREAD

**Issue by epruesse** [vspinu/polymode#135] opened 2017-08-03 04:01 UTC
Outer modes like say Makefiles or Snakefiles often apply variable expansion to the embedded inner mode code. In the case of Makefile recipes, `$` is reserved and indicates that the following word is expanded by Make. To pass `$` to the shell, it is escaped by another `$`:

```Makefile
VAR=bla
something: other
    program $VAR # expands to "program bla"
    VAR=blub; program $$VAR # expands to "program blub"
```

Another example would be Snakemake, which uses Python `string.format` syntax to expand variables in the embedded code, i.e. `{var}` is expanded and curly braces are escaped by doubling them:
```python
rule:
   input: "somefile"
   shell: """
   program {input} # expands to "program somefile"
   program ${{HOME}} # expands to "program ${HOME}"
   """
```

How would you suggest to best write polymodes for those cases? My Lisp isn't strong enough to easily derive specialized modes that change the modes to account for the escape sequences. Is that what would be needed, or is there a simpler way?

**Comment by vspinu** [comment] 2017-08-03 10:02
What exactly do you expect to see within those expansions? I think the expansion is part of the syntax of the parent mode and should be left alone.

**Comment by vspinu** [comment] 2018-08-04 13:44
I am closing this as the intent of the issue is not entirely clear.

**Closed by vspinu** 2018-08-04 13:44 UTC
